server:
  port: 8001
spring:
  application:
    name: provider-ticket
eureka:
  instance:
    prefer-ip-address: true # Register service with ip address
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

